# Generated by Django 4.0.5 on 2022-07-05 03:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_st', models.TextField()),
                ('problem_nm', models.CharField(max_length=50)),
                ('problem_code', models.CharField(max_length=3)),
                ('problem_diff', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Testcases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_input', models.TextField(max_length=1000)),
                ('problem_output', models.TextField(max_length=1000)),
                ('Problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homescr.problems')),
            ],
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_problem', models.CharField(max_length=50)),
                ('problem_code', models.CharField(max_length=3)),
                ('verdict', models.CharField(max_length=20)),
                ('submission_time', models.DateTimeField(verbose_name='submitted_at')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homescr.problems')),
            ],
        ),
    ]
