# Generated by Django 4.0.5 on 2022-07-05 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homescr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions',
            name='solution_lang',
            field=models.CharField(default='c++', max_length=7),
        ),
    ]
