# Generated by Django 4.0.5 on 2022-07-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homescr', '0002_solutions_solution_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions',
            name='problem_diff',
            field=models.CharField(default='easy', max_length=6),
        ),
    ]
