# Generated by Django 4.0.5 on 2022-07-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homescr', '0003_solutions_problem_diff'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutions',
            name='uname',
            field=models.CharField(default='user', max_length=50),
        ),
    ]
