# Generated by Django 4.0.5 on 2022-07-15 16:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homescr', '0005_problems_in_formate_problems_out_formate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcases',
            name='problem_input',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='problem_output',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
