# Generated by Django 4.0.5 on 2022-07-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homescr', '0006_alter_testcases_problem_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcases',
            name='problem_input',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='problem_output',
            field=models.TextField(max_length=1000),
        ),
    ]
