# Generated by Django 4.0.5 on 2022-07-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homescr', '0007_alter_testcases_problem_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='submission_time',
            field=models.DateTimeField(auto_now=True, verbose_name='submitted_at'),
        ),
    ]
