# Generated by Django 4.0.5 on 2022-07-20 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homescr', '0008_alter_solutions_submission_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutions',
            name='submission_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='submitted_at'),
        ),
    ]
